-- 코드를 작성해주세요
WITH PARENT AS
    (SELECT
        PARENT_ID,
        COUNT(*) AS CHILD_COUNT
    FROM
        ECOLI_DATA
    GROUP BY
        PARENT_ID)
SELECT
    ID,
    COALESCE(PARENT.CHILD_COUNT,0) AS CHILD_COUNT
FROM
    ECOLI_DATA
LEFT JOIN
    PARENT
ON
    ECOLI_DATA.ID = PARENT.PARENT_ID;