SELECT
    PRODUCT.PRODUCT_CODE,
    SUM(OFFLINE_SALE.SALES_AMOUNT * PRODUCT.PRICE) AS SALES
FROM
    OFFLINE_SALE
LEFT JOIN
    PRODUCT
ON
    PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY
    PRODUCT_CODE
ORDER BY 2 DESC, 1;