WITH MAX_YEAR AS
(SELECT
    EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAXSIZE
FROM
    ECOLI_DATA
GROUP BY
    YEAR)
SELECT
    EXTRACT(YEAR FROM ECOLI_DATA.DIFFERENTIATION_DATE) AS YEAR,
    MAX_YEAR.MAXSIZE - ECOLI_DATA.SIZE_OF_COLONY AS YEAR_DEV,
    ECOLI_DATA.ID
FROM
    ECOLI_DATA
LEFT JOIN
    MAX_YEAR
ON
    EXTRACT(YEAR FROM ECOLI_DATA.DIFFERENTIATION_DATE) = MAX_YEAR.YEAR
ORDER BY
    YEAR,
    YEAR_DEV;
