-- 코드를 작성해주세요
SELECT
    SUM(HR_GRADE.SCORE) AS SCORE,
    HR_GRADE.EMP_NO AS EMP_NO,
    HR_EMPLOYEES.EMP_NAME AS EMP_NAME,
    HR_EMPLOYEES.POSITION AS POSITION,
    HR_EMPLOYEES.EMAIL AS EMAIL
FROM
    HR_GRADE
LEFT JOIN
    HR_EMPLOYEES
ON
    HR_GRADE.EMP_NO = HR_EMPLOYEES.EMP_NO
GROUP BY
    HR_GRADE.EMP_NO
ORDER BY
    1 DESC
LIMIT
    1