-- 코드를 입력하세요
SELECT
    USED_GOODS_BOARD.TITLE AS TITLE,
    USED_GOODS_BOARD.BOARD_ID AS BOARD_ID,
    USED_GOODS_REPLY.REPLY_ID AS REPLY_ID,
    USED_GOODS_REPLY.WRITER_ID AS WRITER_ID,
    USED_GOODS_REPLY.CONTENTS AS CONTENTS,
    DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_BOARD
JOIN
    USED_GOODS_REPLY
ON
    USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
WHERE
    DATE_FORMAT(USED_GOODS_BOARD.CREATED_DATE,'%Y-%m') = '2022-10'
ORDER BY
    USED_GOODS_REPLY.CREATED_DATE,
    USED_GOODS_BOARD.TITLE;